language: node_js

node_js:
  - '0.12'

before_install:
  - openssl aes-256-cbc -K $encrypted_75a0e4a831d7_key -iv $encrypted_75a0e4a831d7_iv -in .deployment/ci/deploy_id.enc -out .deployment/ci/deploy_id -d
  - chmod 600 .deployment/ci/deploy_id

before_script:
  - npm install

script: grunt

deploy:
  provider: script
  script: .deployment/ci/deploy-to-production.js
  skip_cleanup: true
  on:
    branch: master
