- hosts: all
  remote_user: '{{ remote_user }}'
  sudo: true
  tasks:
    - name: Update APT
      apt: update_cache=yes cache_valid_time=86400

    - name: Ensure NGINX is installed
      apt: name=nginx state=installed

    - name: Create NGINX config
      template: src=nginx.conf dest=/etc/nginx/sites-available/andre.life.conf

    - name: Enable site
      file: state=link path=/etc/nginx/sites-enabled/andre.life.conf src=/etc/nginx/sites-available/andre.life.conf

    - name: Create site dir
      file: state=directory path=/var/www/andre.life owner=www-data group=www-data

    - name: Create default index page
      file: state=file path=/var/www/andre.life/index.html owner=www-data group=www-data

    - name: Install certificate
      shell: |
        certbot certonly \
          --webroot \
          -w /var/www/andre.life \
          -d andre.life \
          -n \
          --agree-tos \
          -m '{{ admin_email }}'

    - name: Restart NGINX
      service: name=nginx state=restarted
