- hosts: all

  become: yes
  become_method: sudo

  vars:
    deploy_user_name: '{{ lookup("file", "{{ secret_dir }}/deploy_user_name") }}'
    deploy_user_ssh_dir: '/home/{{ lookup("file", "{{ secret_dir }}/deploy_user_name") }}/.ssh'

  tasks:
    - name: Create nginx conf.d
      file:
        dest: /etc/nginx/conf.d
        state: directory

    - name: Setup NGINX site config
      template:
        src: ../provision/nginx.conf.tpl
        dest: /etc/nginx/conf.d/site.conf
      register: nginx_conf

    - name: Setup deploy user
      user:
        name: '{{ deploy_user_name }}'
        password: '!'
        append: yes
        groups:
          - www-data

    - name: Setup deploy user authorized_key
      authorized_key:
        key: '{{ lookup("file", "{{ secret_dir }}/deploy_user_id_rsa.pub") }}'
        user: '{{ deploy_user_name }}'

    - name: Create web root
      file:
        dest: /var/www
        state: directory
        owner: '{{ deploy_user_name }}'
        group: www-data
        mode: 0755

    - name: Copy build to server
      synchronize:
        src: ../build/
        dest: /var/www
        delete: yes

    - name: Setup build owner
      file:
        dest: /var/www
        owner: '{{ deploy_user_name }}'
        group: www-data
        recurse: yes

    - name: Pass NGINX conf to container
      when: nginx_conf.changed
      local_action: >-
        command yc compute instance update-container \
            --name "{{ machine_name }}" \
            --container-volume-host-path 'name=site-conf,mount-path=/etc/nginx/conf.d,host-path=/etc/nginx/conf.d,ro=true'
      become: no
      register: container_conf

    - name: Show NGINX conf to container result
      when: container_conf.changed
      debug:
        msg: "{{ container_conf }}"

    - name: Restart VM
      when: nginx_conf.changed
      local_action: command yc compute instance restart --name "{{ machine_name }}"
      become: no
      register: restart_vm

    - name: Show Restart VM result
      when: restart_vm.changed
      debug:
        msg: "{{ restart_vm }}"
