name: Create site release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm ci
    - run: npm run build
    - run: cd build && tar -cvzf ../build.tar.gz . && cd ..
    - uses: actions/upload-artifact@v1
      with:
        name: build.tar.gz
        path: build.tar.gz
        retention-days: 1
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'build.'
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Store upload URL
        run: echo -n "${{ steps.create_release.outputs.upload_url }}" > upload-url.txt
      - uses: actions/upload-artifact@v1
        with:
          name: upload-url.txt
          path: upload-url.txt
          retention-days: 1
  attach_build:
    needs:
      - build
      - create_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - name: Get upload URL
        id: upload_url
        run: cat upload-url.txt | xargs -I{} echo "::set-output val={}"
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.upload_url.val }}
          asset_path: build.tar.gz
          asset_name: build.tar.gz
          asset_content_type: application/gzip
